dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install django
  - pip install django-opentracing
  - pip install wavefront-opentracing-sdk-python
  - pip install flake8 flake8-colors flake8-import-order
  - pip install pep8-naming
  - pip install pydocstyle
  - pip install pylint
before_script:
  - python -m flake8
  - python -m pylint wavefront_sdk
  - python -m pydocstyle
script:
  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
      test -n "$(git diff -G version= $TRAVIS_COMMIT_RANGE setup.py)";
    fi
deploy:
  - provider: pypi
    user: wavefront-cs
    server: https://test.pypi.org/legacy/
    password:
      secure: "w4j8TyINfzCRlcXiZcYj7eIcEYmYIisSHxUsXqC+7pUCFfAwOSJEQJhkYepFWxcmxOIhY5IdWOGsU1JNBkFyzS3NNlU76xvZ7Ykl5zicVd3ng6i/Pj6Eswhf2B5BgCpQwWIXAEHPQL+Q6xmY9tL4YnaLTpXsOOliltt1qdc+W31DilnCEmoFpDUK/KEQckRMvFj60mk3dsep87jxQdtuF+we0piN0JdG5KawjYbwbsLo940ZkXittRw5WKfcIwYbZo1SU8fxflvLKX48qbz6vK9+ACYL/3gav2x2zdopNx8mmK17Q5zgNKuvSm686gXZgzJGrNaSNFm3oNmRMP0dBS4ebYR+jS7ABOiT0SekwBqWkVKLEMnaJC/1k/8JuKabeXcA9mmZP/ZhmRsVMtyP449RBEQKoditMLr10PZbiz5iDu0UjqrF7yOqxwEsIUI7lBXY4r1FBxIrAD/xU8SMFurmb/qTmwB8sbmHxX/L6HBY0giiN039KqhAvcwPbSuDYchzyHouXRkhMgpI2jtpOVottEzMyJtRqaK+qV5zdm1ST6E7WqaIvEkkNM7OGw6jxexTadhQ7w4xdjHYIcgDHHFZJ3C8ZgivaiGaLNxrTT+OJ3fwc+zGcT6ndvYYGzXusre56Zal/PbdElv+sqX0sS/U5UVv9cJU5qQYIv3lpsI="
    on:
      python: 3.7
  - provider: pypi
    user: wavefront-cs
    password:
      secure: "mm5C+7lnAlHwS1Wd8EIHbGj44qxweHEvyi4PNrhUOSo2Fd04m+EDXZHAXddKZiTdQSl0ZtlA4brlGYrx2CNBvNVKzfyWDnotQsfxlwSGZtvos10DSs1q3wtCAG2AVFBS6zdqza4qgy2GTMB8gdL6/8L1Yfht5nDSZDf6Z95QuoJgXuBTEmGTGIPmctUF/GTky/WXJv2X0appUxRoyypKNVjn3wkquEJIqddmEuH8fSF94qKwo2UNwg2HjCGGk6LiYA7WjoUIipxxpd1eQaHiogvdwUYj1CpvHWi+tENNHh2dmFd/pGRbgxxQ0K7NVLlIErafu41e/5wBaFL2qbfTFYK10B0Nv0F+gYhW/9/mRTS7ourJOWHWt5lOLPzDk9wpMU2U8oxeA5T5sal9MhKCAMWFNpiD8/Z8K0fYQDhTH5Vvh1zA6YSzwDvvZHCjuxzqlIccj1EwMsKnHTED9kbZDMok7rJ6Yv3e3GG9ULzFdgOcP5/Rk4POh36djD25E62emtghCmQE83uQg6iGsOVSCcmkAxnQJ4d/PvhuwpeqSFCjU3T76u70hST82u18Cp5O8DUwF+AyzQFx04Y2YQYsS2w589Mk58Qt6KVV+x+fTecfXfHlLJ33NbOftXFBlJZr5Kod7yM163FfwEOgq+FTqaEsn38Lo/8D+riGnKFjRrE="
    on:
      python: 3.7
      tags: true
